import fs from "fs/promises";
import path from "path";
import { fileURLToPath } from "url";

import { Profile } from "../../models/profile.model.js";
import { User } from "../../models/user.model.js";
import {
    ADMIN,
    DEMO_PASSWORD,
    INSTRUCTORS,
    STUDENTS,
    avatarFor
} from "../data/people.js";

const here = path.dirname(fileURLToPath(import.meta.url));

//Written on every run so the file can never drift from the database. The path
//is gitignored - these are throwaway demo logins, but a credentials file in a
//repository is a bad habit regardless of what it contains.
const writeCredentials = async () => {
    const row = (person, role) =>
        `| ${person.firstName} ${person.lastName} | ${role} | \`${person.email}\` |`;

    const contents = [
        "# Demo account credentials",
        "",
        "Generated by `npm run seed`. Not tracked in git; regenerated on every run.",
        "",
        `Every account below shares the same password: \`${DEMO_PASSWORD}\``,
        "",
        "| Name | Role | Email |",
        "| --- | --- | --- |",
        row(STUDENTS[0], "Student (primary demo login)"),
        ...STUDENTS.slice(1).map((person) => row(person, "Student")),
        ...INSTRUCTORS.map((person) => row(person, "Instructor")),
        row(ADMIN, "Admin"),
        "",
        `Sign in at \`/login\`. ${STUDENTS[0].firstName} ${STUDENTS[0].lastName} is the account`,
        "carrying enrolments, progress and purchase history.",
        ""
    ].join("\n");

    await fs.writeFile(path.join(here, "..", "CREDENTIALS.md"), contents, "utf8");
}

//Creates one user and the profile it points at.
//
//User.create() rather than insertMany() is deliberate: the password is hashed
//by a pre("save") hook, and bulk inserts bypass hooks entirely. An account
//seeded that way looks fine in the database and can never log in.
const createPerson = async (person, accountType) => {
    const profile = await Profile.create({
        gender : person.gender,
        dateOfBirth : person.dateOfBirth,
        about : person.about,
        contactNumber : person.contactNumber
    });

    const user = await User.create({
        firstName : person.firstName,
        lastName : person.lastName,
        email : person.email,
        password : DEMO_PASSWORD,
        accountType,
        //instructors are gated on approval; the seed ships them ready to teach
        approved : true,
        active : true,
        additionalDetails : profile._id,
        image : avatarFor(person.firstName, person.lastName),
        courses : [],
        courseProgress : []
    });

    return user;
}

const run = async () => {
    const instructors = {};
    const students = {};

    for (const person of INSTRUCTORS) {
        instructors[person.key] = await createPerson(person, "Instructor");
    }

    for (const person of STUDENTS) {
        students[person.key] = await createPerson(person, "Student");
    }

    const admin = await createPerson(ADMIN, "Admin");

    await writeCredentials();

    console.log(`  ${Object.keys(instructors).length} instructors`);
    console.log(`  ${Object.keys(students).length} students`);
    console.log(`  1 admin`);
    console.log(`  credentials written to seed/CREDENTIALS.md (gitignored)`);

    //Later phases reference these by key rather than re-querying.
    return { instructors, students, admin };
}

export default { title : "People", run };
